export const UNIT01_TAXONOMY_BUNDLE = {
  unitId: "unit01",
  grammarCategory: "수일치",
  unitTitle: "주어와 동사의 수일치",
  selectionPatterns: ["is/are", "has/have", "does/do", "was/were"],
  coreQuestion: "진짜 주어 또는 선행사가 누구인가?",
  points: [
    {
      pointId: "unit01_point01",
      pointTitle: "주어와 수식어를 구별하라",
      coreDecisionPoint: "수식어구를 걷어내고 핵심 주어를 찾는다",
      rows: [
        {
          id: "gu_sva_modifier_prep_001",
          grammarCategory: "수일치",
          grammarPoint: "주어 뒤 전명구 수식어와 주어 구별",
          structurePattern: "주어 + (전치사 + 명사) + 동사",
          decisionPoint: "전명구 안 명사를 버리고 진짜 주어를 찾는다",
          explanationShort: "주어 뒤 전명구는 수식어구이므로 그 안의 명사와 동사를 일치시키지 않는다.",
          explanationFull: "전치사구는 주어를 꾸미는 정보일 뿐이다. 동사는 전치사 뒤 명사가 아니라 문장의 핵심 주어와 수일치해야 한다.",
          examplePatternType: "two_choice",
          authoringMode: "auto_lite",
          selectionPatterns: ["is/are", "has/have", "was/were", "does/do"],
          exampleBase: "The cost of living in urban areas is comparatively high.",
          exampleTransforms: ["주어에 밑줄 긋기", "동사 선택형", "밑줄 O/X"],
          commonTraps: ["전치사 뒤 복수명사를 주어로 착각", "가까운 명사에 끌려 복수동사를 선택"],
          tags: ["수일치", "전명구", "주어 찾기", "가까운 명사 함정"],
        },
        {
          id: "gu_sva_modifier_ving_tov_002",
          grammarCategory: "수일치",
          grammarPoint: "주어 뒤 v-ing / to-v 수식어구와 주어 구별",
          structurePattern: "주어 + (v-ing ~ / to-v ~) + 동사",
          decisionPoint: "준동사구 전체를 수식어로 보고 주어만 남긴다",
          explanationShort: "주어 뒤의 현재분사구나 to부정사구는 주어를 수식할 뿐, 동사의 수를 결정하지 않는다.",
          explanationFull: "showing, crashing, to show 같은 준동사구는 명사를 뒤에서 꾸미는 형용사 역할이다. 준동사구 내부의 명사나 동사를 주어로 보면 안 된다.",
          examplePatternType: "two_choice",
          authoringMode: "auto_lite",
          selectionPatterns: ["is/are", "make/makes", "was/were"],
          exampleBase: "The museum showing many priceless paintings is a major tourist attraction.",
          exampleTransforms: ["선택형", "주어 찾기", "밑줄 오류 수정"],
          commonTraps: ["showing/crashing을 문장 동사로 착각", "준동사구 안의 복수명사에 끌림"],
          tags: ["수일치", "현재분사구", "to부정사구", "주어 찾기"],
        },
        {
          id: "gu_sva_modifier_pp_003",
          grammarCategory: "수일치",
          grammarPoint: "주어 뒤 p.p. 수식어구와 주어 구별",
          structurePattern: "주어 + (p.p. ~) + 동사",
          decisionPoint: "과거분사구는 주어를 수식하는 정보로만 처리한다",
          explanationShort: "주어 뒤의 과거분사구는 수식어구이므로 동사는 그 앞의 주어와 수일치한다.",
          explanationFull: "dressed, made, found 같은 과거분사는 문장 동사가 아니라 주어를 뒤에서 꾸미는 형용사 역할일 수 있다. 분사구를 걷어내고 핵심 주어를 먼저 잡아야 한다.",
          examplePatternType: "two_choice",
          authoringMode: "auto_lite",
          selectionPatterns: ["is/are", "belongs/belong", "was/were"],
          exampleBase: "Products made from milk are full of protein and calcium.",
          exampleTransforms: ["네모 어법", "O/X 판단", "주어 표시 후 동사 선택"],
          commonTraps: ["p.p.를 본동사로 오해", "분사 뒤 명사에 끌려 수일치 오류"],
          tags: ["수일치", "과거분사구", "주어 찾기", "분사 함정"],
        }
      ],
    },
    {
      pointId: "unit01_point02",
      pointTitle: "주격 관계대명사절 내 동사의 수는 선행사를 찾아라",
      coreDecisionPoint: "관계사절 동사의 수는 관계대명사의 선행사로 결정한다",
      rows: [
        {
          id: "gu_sva_relsubj_basic_001",
          grammarCategory: "수일치",
          grammarPoint: "주격 관계대명사절의 동사 수일치",
          structurePattern: "선행사 + 관계대명사 + 동사",
          decisionPoint: "관계대명사가 주어인 절에서는 동사를 선행사와 수일치시킨다",
          explanationShort: "주격 관계대명사절의 동사는 관계대명사의 선행사와 수일치한다.",
          explanationFull: "who, which, that이 관계사절 안에서 주어 역할을 할 때, 그 뒤 동사는 관계대명사 자체가 아니라 앞의 선행사를 기준으로 단수/복수를 정한다.",
          examplePatternType: "two_choice",
          authoringMode: "auto_lite",
          selectionPatterns: ["is/are", "lives/live", "becomes/become"],
          exampleBase: "We usually get along best with people who are like us.",
          exampleTransforms: ["선행사에 밑줄 긋기", "동사 선택형", "밑줄 O/X"],
          commonTraps: ["관계대명사 바로 뒤 동사를 독립적으로 판단", "뒤쪽 명사나 보어에 끌려 수일치 판단"],
          tags: ["수일치", "관계대명사", "선행사", "주격 관계대명사절"],
        },
        {
          id: "gu_sva_relsubj_with_modifier_002",
          grammarCategory: "수일치",
          grammarPoint: "수식어구가 낀 선행사와 주격 관계대명사절의 수일치",
          structurePattern: "선행사 + 수식어구 + 관계대명사 + 동사",
          decisionPoint: "선행사 뒤 수식어구를 제거하고 진짜 선행사를 찾는다",
          explanationShort: "선행사를 뒤에서 수식하는 어구 안의 명사를 선행사로 착각하지 않는다.",
          explanationFull: "전명구나 다른 수식어구가 선행사 뒤에 끼어 있으면, 관계사절 동사의 수는 그 수식어구 안 명사가 아니라 원래 선행사와 일치해야 한다.",
          examplePatternType: "two_choice",
          authoringMode: "manual_deep",
          selectionPatterns: ["contain/contains", "don't/doesn't"],
          exampleBase: "Throw away all documents in the cabinet which contain outdated information.",
          exampleTransforms: ["선행사 찾기", "수식어구 제거 후 문장 뼈대 복원", "틀린 동사 고치기"],
          commonTraps: ["in the cabinet의 cabinet을 선행사로 착각", "가까운 단수명사에 끌려 단수동사 선택"],
          tags: ["수일치", "관계대명사", "수식어구", "선행사 찾기"],
        }
      ],
    },
  ],
};
