-- supabase/migrations/20260331115857_grammar_unit_taxonomy_unit01_seed.sql

alter table public.grammar_unit_taxonomy
  add column if not exists unit_id text,
  add column if not exists point_id text,
  add column if not exists selection_patterns text[] not null default '{}',
  add column if not exists example_base text not null default '',
  add column if not exists example_transforms text[] not null default '{}',
  add column if not exists common_traps text[] not null default '{}',
  add column if not exists difficulty text not null default 'basic';

insert into public.grammar_unit_taxonomy (
  id,
  unit_id,
  point_id,
  grammar_category,
  grammar_point,
  structure_pattern,
  decision_point,
  explanation_short,
  explanation_full,
  example_pattern_type,
  authoring_mode,
  difficulty,
  selection_patterns,
  example_base,
  example_transforms,
  common_traps,
  tags,
  is_active
) values
(
  'gu_sva_modifier_prep_001',
  'unit01',
  'unit01_point01',
  '수일치',
  '주어 뒤 전명구 수식어와 주어 구별',
  '주어 + (전치사 + 명사) + 동사',
  '전명구 안 명사를 버리고 진짜 주어를 찾는다',
  '주어 뒤 전명구는 수식어구이므로 그 안의 명사와 동사를 일치시키지 않는다.',
  '전치사구는 주어를 꾸미는 정보일 뿐이다. 동사는 전치사 뒤 명사가 아니라 문장의 핵심 주어와 수일치해야 한다.',
  'two_choice',
  'auto_lite',
  'basic',
  array['is/are','has/have','was/were','does/do'],
  'The cost of living in urban areas is comparatively high.',
  array['주어에 밑줄 긋기','동사 선택형','밑줄 O/X'],
  array['전치사 뒤 복수명사를 주어로 착각','가까운 명사에 끌려 복수동사를 선택'],
  array['수일치','전명구','주어 찾기','가까운 명사 함정'],
  true
),
(
  'gu_sva_modifier_ving_tov_002',
  'unit01',
  'unit01_point01',
  '수일치',
  '주어 뒤 v-ing / to-v 수식어구와 주어 구별',
  '주어 + (v-ing ~ / to-v ~) + 동사',
  '준동사구 전체를 수식어로 보고 주어만 남긴다',
  '주어 뒤의 현재분사구나 to부정사구는 주어를 수식할 뿐, 동사의 수를 결정하지 않는다.',
  'showing, crashing, to show 같은 준동사구는 명사를 뒤에서 꾸미는 형용사 역할이다. 준동사구 내부의 명사나 동사를 주어로 보면 안 된다.',
  'two_choice',
  'auto_lite',
  'basic',
  array['is/are','make/makes','was/were'],
  'The museum showing many priceless paintings is a major tourist attraction.',
  array['선택형','주어 찾기','밑줄 오류 수정'],
  array['showing/crashing을 문장 동사로 착각','준동사구 안의 복수명사에 끌림'],
  array['수일치','현재분사구','to부정사구','주어 찾기'],
  true
),
(
  'gu_sva_modifier_pp_003',
  'unit01',
  'unit01_point01',
  '수일치',
  '주어 뒤 p.p. 수식어구와 주어 구별',
  '주어 + (p.p. ~) + 동사',
  '과거분사구는 주어를 수식하는 정보로만 처리한다',
  '주어 뒤의 과거분사구는 수식어구이므로 동사는 그 앞의 주어와 수일치한다.',
  'dressed, made, found 같은 과거분사는 문장 동사가 아니라 주어를 뒤에서 꾸미는 형용사 역할일 수 있다. 분사구를 걷어내고 핵심 주어를 먼저 잡아야 한다.',
  'two_choice',
  'auto_lite',
  'basic',
  array['is/are','belongs/belong','was/were'],
  'Products made from milk are full of protein and calcium.',
  array['네모 어법','O/X 판단','주어 표시 후 동사 선택'],
  array['p.p.를 본동사로 오해','분사 뒤 명사에 끌려 수일치 오류'],
  array['수일치','과거분사구','주어 찾기','분사 함정'],
  true
),
(
  'gu_sva_modifier_relative_004',
  'unit01',
  'unit01_point01',
  '수일치',
  '주어 뒤 관계사절/형용사구와 주어 구별',
  '주어 + (관계사절 / 형용사구) + 동사',
  '관계사절과 형용사구를 제거하고 선행 주어를 확인한다',
  '관계사절과 형용사구는 주어를 설명하는 수식어구이므로 동사의 수를 결정하지 않는다.',
  'that have a special function, full of complex equations 같은 부분은 명사를 꾸미는 덩어리이다. 동사는 그 덩어리 안 명사가 아니라 원래 주어와 맞아야 한다.',
  'two_choice',
  'manual_deep',
  'intermediate',
  array['is/are','hit/hits'],
  'A book full of complex equations is essential for learning advanced math.',
  array['선행 주어 찾기','선택형','틀린 부분 고치기'],
  array['관계사절 내부 명사를 주어로 착각','형용사구 끝 명사에 끌림'],
  array['수일치','관계사절','형용사구','선행 주어'],
  true
),
(
  'gu_sva_modifier_parenthetical_005',
  'unit01',
  'unit01_point01',
  '수일치',
  '삽입어구/삽입절이 있는 문장의 수일치',
  '주어 + 삽입어구/삽입절 + 동사',
  '콤마나 대시로 묶인 삽입부를 제거하고 주어를 찾는다',
  '삽입어구나 삽입절은 주어를 보충 설명할 뿐이므로 동사의 수와 직접 관련이 없다.',
  'who has worked..., a strategic partnership..., predicting... 같은 삽입 정보는 문장의 뼈대가 아니다. 삽입부를 들어내고 주어와 동사만 남겨 수일치를 판단한다.',
  'sentence_based',
  'manual_deep',
  'advanced',
  array['is/are','has/have'],
  'A key witness, who has worked with the victim for over 10 years, is going to appear in court.',
  array['콤마 삽입구 제거','문장 뼈대 복원','선택형'],
  array['삽입절 속 명사를 주어로 착각','콤마 뒤 정보에 끌려 복수동사 선택'],
  array['수일치','삽입어구','삽입절','문장 뼈대 복원'],
  true
),
(
  'gu_sva_relsubj_basic_001',
  'unit01',
  'unit01_point02',
  '수일치',
  '주격 관계대명사절의 동사 수일치',
  '선행사 + 관계대명사 + 동사',
  '관계대명사가 주어인 절에서는 동사를 선행사와 수일치시킨다',
  '주격 관계대명사절의 동사는 관계대명사의 선행사와 수일치한다.',
  'who, which, that이 관계사절 안에서 주어 역할을 할 때, 그 뒤 동사는 관계대명사 자체가 아니라 앞의 선행사를 기준으로 단수/복수를 정한다.',
  'two_choice',
  'auto_lite',
  'basic',
  array['is/are','lives/live','becomes/become'],
  'We usually get along best with people who are like us.',
  array['선행사에 밑줄 긋기','동사 선택형','밑줄 O/X'],
  array['관계대명사 바로 뒤 동사를 독립적으로 판단','뒤쪽 명사나 보어에 끌려 수일치 판단'],
  array['수일치','관계대명사','선행사','주격 관계대명사절'],
  true
),
(
  'gu_sva_relsubj_with_modifier_002',
  'unit01',
  'unit01_point02',
  '수일치',
  '수식어구가 낀 선행사와 주격 관계대명사절의 수일치',
  '선행사 + 수식어구 + 관계대명사 + 동사',
  '선행사 뒤 수식어구를 제거하고 진짜 선행사를 찾는다',
  '선행사를 뒤에서 수식하는 어구 안의 명사를 선행사로 착각하지 않는다.',
  '전명구나 다른 수식어구가 선행사 뒤에 끼어 있으면, 관계사절 동사의 수는 그 수식어구 안 명사가 아니라 원래 선행사와 일치해야 한다.',
  'two_choice',
  'manual_deep',
  'intermediate',
  array['contain/contains','don''t/doesn''t'],
  'Throw away all documents in the cabinet which contain outdated information.',
  array['선행사 찾기','수식어구 제거 후 문장 뼈대 복원','틀린 동사 고치기'],
  array['in the cabinet의 cabinet을 선행사로 착각','가까운 단수명사에 끌려 단수동사 선택'],
  array['수일치','관계대명사','수식어구','선행사 찾기'],
  true
),
(
  'gu_sva_relsubj_semantic_003',
  'unit01',
  'unit01_point02',
  '수일치',
  '의미 자연성으로 선행사 판별',
  '복수 후보 명사 + 관계대명사 + 동사',
  '관계대명사 자리에 넣어 해석했을 때 가장 자연스러운 명사를 선행사로 잡는다',
  '앞의 명사가 둘 이상이면 문맥상 가장 자연스럽게 수식되는 명사가 선행사이다.',
  '관계사절은 앞의 아무 명사나 꾸미는 것이 아니다. 관계대명사 자리에 후보 명사를 각각 넣어 보며 뜻이 자연스러운 것을 선행사로 확정해야 한다.',
  'sentence_based',
  'manual_deep',
  'advanced',
  array['was/were','contain/contains'],
  'Try the pie on the table which was made by my grandmother.',
  array['선행사 후보 비교','왜 다른 명사가 선행사 X인지 설명','문맥 기반 선택형'],
  array['관계대명사 바로 앞 명사를 무조건 선행사로 판단','문법만 보고 의미 확인을 생략'],
  array['수일치','관계대명사','선행사','의미 자연성','함정'],
  true
),
(
  'gu_sva_relsubj_compound_004',
  'unit01',
  'unit01_point02',
  '수일치',
  'and로 연결된 복합 선행사와 주격 관계대명사절',
  'A and B + 관계대명사 + 동사',
  '복합 선행사가 복수 개념이면 관계사절 동사도 복수로 맞춘다',
  '복합 선행사가 복수이면 관계사절의 동사도 복수형을 쓴다.',
  '관계사절 안 동사는 선행사의 수를 따른다. 선행사가 rainforests and all the animals처럼 복합 복수 구조면 관계사절 동사도 lives가 아니라 live가 된다.',
  'two_choice',
  'auto_lite',
  'basic',
  array['live/lives','are/is'],
  'I love the rainforests and all the animals that live there.',
  array['복합 선행사 표시','관계사절 동사 선택','내신형 밑줄 오류 찾기'],
  array['가장 가까운 단수명사처럼 오해','관계사절만 보고 동사를 단수로 오판'],
  array['수일치','관계대명사','복합 선행사','and'],
  true
)
on conflict (id) do update set
  unit_id = excluded.unit_id,
  point_id = excluded.point_id,
  grammar_category = excluded.grammar_category,
  grammar_point = excluded.grammar_point,
  structure_pattern = excluded.structure_pattern,
  decision_point = excluded.decision_point,
  explanation_short = excluded.explanation_short,
  explanation_full = excluded.explanation_full,
  example_pattern_type = excluded.example_pattern_type,
  authoring_mode = excluded.authoring_mode,
  difficulty = excluded.difficulty,
  selection_patterns = excluded.selection_patterns,
  example_base = excluded.example_base,
  example_transforms = excluded.example_transforms,
  common_traps = excluded.common_traps,
  tags = excluded.tags,
  is_active = excluded.is_active;
